on:
  push:
    branches:
      - master
      - devel
  schedule:
    # run every day at 9PM
    - cron: '0 21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish base to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: facilebio/facilebio_base
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: facilebio_base
