on:
  push:
    branches:
      - master
      - devel
    paths:
      - 'facilebio/**'
  schedule:
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
    # https://crontab.guru/ to debug cron syntax
    # run every day at 4:00 AM Pacific Time (which is 11 AM UTC)
    - cron: '0 16,12 * * *'
jobs:
  build-facilebio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish facilebio to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: facilebio/facilebio
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: facilebio
  