on:
  push:
    branches:
      - master
      - devel
    paths:
      - 'facilebio_base/**'
  schedule:
    # run every day at 1:00 AM
    - cron: '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish base to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: facilebio/facilebio_base
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: facilebio_base
